envelope-zero/backend

.github/workflows/renovate-config-validator.yml
This should fix the action being triggered for all pushes
=> test: only run renovate config check when file changes

renovate.json
This will make renovate run `go mod tidy` on **all** updates, satisfying the pre-commit hook.
=> chore(renovate): enable go mod tidy

.github/workflows/build.yml
This will fix the build workflow failing for PRs from forks due to missing permissions.
=> test: do not push image for non-tag refs that are not main

.github/workflows/build.yml, .gitignore, CONTRIBUTING.md, Dockerfile, Makefile, internal/controllers/main_list_test.go, internal/controllers/main_options_test.go, internal/controllers/routing.go
This adds the `/version` endpoint which has the version set at build. The configuration is as follows:
* `make build` uses the long hash of the git HEAD as default
* The `Dockerfile` uses `0.0.0` as default. This will only be used when someone runs `docker build` directly, which is not recommended.
* The GitHub action building the image for releases uses the GitHub context `github.ref_name`, which is the branch or tag name.
Resolves #56.
=> feat: add version endpoint

internal/controllers/routing.go
With this zerolog is used to print the routes in gin debug mode.
Resolves #68.
=> feat: use zerolog for debug route printing

internal/controllers/routing.go
Do not trust any proxy and do not process the X-Forwarded-For header. We do not do anything with client IPs, therefore we don’t need to process them
Resolves #55.
=> feat: trust no proxy

internal/controllers/main_list_test.go, internal/controllers/routing.go, internal/test/helpers.go
Return HTTP 405 if there is a matching route, but it does not support the request method
=> feat: use HTTP 405 responses for existing routes that don’t support a method

README.md, internal/controllers/helper.go, internal/controllers/helper_test.go
Use the x-forwarded-prefix header to add a prefix if it is set. 
Resolves #86.
=> feat: use x-forwarded-prefix to generate links

internal/controllers/account.go, internal/controllers/account_test.go
When there are no accounts, an empty list should be returned, not `nil` (`null` in JSON).
=> fix: return empty list, not null if there are no accounts

internal/controllers/routing.go, internal/controllers/routing_test.go, internal/test/helpers.go, main.go
This moves the configuration to the router initialization, which makes it configurable for tests, too.
=> chore: move configuration to router initialization

internal/controllers/account.go, internal/controllers/account_test.go, internal/controllers/allocation.go, internal/controllers/allocation_test.go, internal/controllers/budget.go, internal/controllers/budget_test.go, internal/controllers/category.go, internal/controllers/category_test.go, internal/controllers/envelope.go, internal/controllers/envelope_test.go, internal/controllers/helper.go, internal/controllers/helper_test.go, internal/controllers/main_error_handler_test.go, internal/controllers/transaction.go, internal/controllers/transaction_test.go, internal/test/helpers.go, internal/test/helpers_test.go
This contains multiple commits, improving tests and resolving #89.
- test: improve tests with better output and less cross-dependencies
- fix: return 404 for endpoints of non-existing budgets
- test: deduplicate test code
- fix: verify that parent resource exists before returning child
=> fix: return 404 instead of empty list for non-existing parent

internal/controllers/account.go, internal/controllers/account_test.go, internal/controllers/allocation.go, internal/controllers/allocation_test.go, internal/controllers/budget_test.go, internal/controllers/category_test.go, internal/controllers/envelope_test.go, internal/controllers/helper.go, internal/controllers/transaction.go, internal/controllers/transaction_test.go
With this PR, all GET endpoints for a single resource verify that the resource belongs to the specified parent.
Resolves #90.
=> fix: check parent for account

internal/controllers/all.go, internal/controllers/envelope.go, internal/controllers/envelope_test.go, internal/controllers/helper.go, internal/models/account.go, internal/models/all.go, internal/models/all_test.go, internal/models/envelope.go, internal/models/envelope_test.go
Querying an envelope with a month in the `YYYY-MM` format now returns spending information about that month.
Resolves #39.
=> feat: add spent sum per envelope per month

internal/controllers/envelope.go, internal/controllers/envelope_test.go
Adds a `balance` field to the envelope month endpoint that returns the balance for the envelope for the requested month.
=> feat: add balance for envelopes

.github/.codecov.yml, .github/semantic.yml
This allows PRs with marginally less coverage than before. The diff must be covered by at least 10% less than the base branch overall.
=> test: update codecov config

renovate.json
This allows renovate to automatically upgrade minor versions for GitHub actions.
=> feat: automerge minor GitHub actions upgrades

internal/controllers/main_test.go, internal/models/main_test.go
Tests now run locally again and actually delete the DB afterwards.
=> fix: defer is not called on os.Exit, wrap main test function

.gitignore
We’re now also ignoring any node related files.
=> fix: ignore node files

.github/workflows/renovate-config-validator.yml
With this, the workflow should only run when the workflow or the config itself change.
This will reduce the number of unneeded action runs.
=> test: only run renovate config validator when the workflow or the config change

.goreleaser.yaml
=> build: goreleaser now sets the build args correctly

.github/workflows/go-test-and-release.yml
This logs in to the registry. Goreleaser itself does this, but the action does not.
=> fix: log in to github registry

.github/workflows/build.yml, .github/workflows/go-test-and-release.yml, .goreleaser.yaml
This will get us back to functioning builds. Will likely be debugged at some point.
>     ⨯ release failed after 379.81s error=docker images: failed to publish
>	artifacts: failed to push ghcr.io/envelope-zero/backend:v0.20.5:
>	exit status 1: The push refers to repository [ghcr.io/envelope-zero/backend]
> 9c19cdb2b096: Preparing
> denied: unauthenticated: User cannot be authenticated with the token provided.
=> fix: roll back to the separate build workflow

.github/workflows/renovate-config-validator.yml
On tags, the paths are not evaluated.
=> test: only run renovate config validator on main and PRs to main

.github/.codecov.yml
Ignoring the test helpers in the future as those are tested by the tests themselves
=> test: codecov: ignore test helpers

README.md, internal/httputil/error_test.go, internal/httputil/options_test.go, internal/httputil/request.go, internal/httputil/request_test.go, internal/test/helpers.go, internal/test/helpers_test.go
=> feat: default prefix to /api if reverse proxy is used

internal/models/database.go
With this, `SQLITE_BUSY` errors are prevented if multiple queries occur rapidly.
=> fix: limit parallel connections to database to 1

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/models/budget.go
This will facilitate the frontend implementation. The actual value is not computed as of now.
=> feat: add balance field to budget

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/account.go, pkg/controllers/allocation.go, pkg/controllers/budget.go, pkg/controllers/category.go, pkg/controllers/envelope.go, pkg/controllers/transaction.go
Fixes the API documentation to use strings, not uint64 as ID value.
=> fix: type of IDs in API docs

.github/.codecov.yml
This allows code coverage of diff to be 25% less than total coverage. This is sometimes needed for small changes containing untestable error handling.
=> test: allow code coverage of diff to be 25% less than total coverage

pkg/httputil/request.go
Fixes broken links when running locally (http.Request is weird)
=> fix: broken links when running locally

.vscode/launch.json, main.go, pkg/controllers/account.go, pkg/controllers/account_test.go, pkg/controllers/allocation.go, pkg/controllers/allocation_test.go, pkg/controllers/budget.go, pkg/controllers/category.go, pkg/controllers/category_test.go, pkg/controllers/envelope.go, pkg/controllers/envelope_test.go, pkg/controllers/main_test.go, pkg/controllers/transaction.go, pkg/controllers/transaction_test.go, pkg/models/account_test.go, pkg/models/envelope_test.go, pkg/models/main_test.go, pkg/test/helpers.go
This enables foreign keys for SQLite. As they cannot be null, tests needed to be updated. This will also break the current frontend version (0.14.0)
=> feat: enable foreign keys for SQLite

api/docs.go, api/swagger.json, api/swagger.yaml, internal/database/database.go, internal/router/router.go, pkg/controllers/account.go, pkg/controllers/account_test.go, pkg/controllers/budget.go, pkg/controllers/types.go, pkg/httputil/error.go, pkg/httputil/error_test.go, pkg/httputil/query.go, pkg/httputil/query_test.go, pkg/httputil/request.go, pkg/httputil/request_test.go
Adds filtering for accounts. 
This adds a workaround for gin not being able to bind custom fields. The resolution of the workaround is tracked in #223.
=> feat: add query filtering for accounts

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/budget.go, pkg/controllers/envelope.go, pkg/models/account.go, pkg/models/allocation.go, pkg/models/budget.go, pkg/models/category.go, pkg/models/envelope.go, pkg/models/model.go, pkg/models/transaction.go
Adds examples to all values, defaults to non-required values an descriptions to complex values.
=> docs: add missing swagger types and examples

pkg/controllers/category_test.go, pkg/controllers/envelope.go
Empty arrays are easier for clients to work with instead of needing to check for null values.
=> fix: when no envelopes are present for a category, return an empty array, not null

.goreleaser.yaml
With this PR, goreleaser will again correctly set the version with a linker flag
=> fix: goreleaser did not set the version correctly on builds

.goreleaser.yaml
Fixes a copy-pasting error when fixing goreleaser setting the version with a linker flag
=> fix: bad copy paste

internal/router/middleware.go, internal/router/middleware_test.go, internal/router/router.go
With this, requestURL is unused and therefore removed.
=> fix: use baseURL instead of requestURL for /v1 endpoint

pkg/controllers/transaction.go, pkg/controllers/transaction_test.go, pkg/httputil/query_test.go
This enforces the checking of envelope IDs being set for updates of transactions, too.
=> fix: ensure envelope can only be set to nil for transfers

pkg/controllers/transaction.go, pkg/controllers/transaction_test.go
Sort transactions by reverse date order.
Resolves #181.
=> feat: sort transactions from newest to oldest

Dockerfile, renovate.json
With this PR, renovate will upgrade the version of go in one PR for all occurences.
=> chore: upgrade go version everywhere at once

renovate.json
This cleans up the renovate configuration a bit.
=> chore: remove unneeded spaces for gofumpt, go.mod go version

renovate.json
This adds the language-version in .golangci.yml to the go group so that go is upgraded at once.
=> chore: add golangci go version to go group

renovate.json
Removes the extractVersion for .golangci.yml as this can apparently be autodetected.
=> chore: remove extractVersion for .golangci.yml

pkg/controllers/transaction.go, pkg/controllers/transaction_test.go
This removes the requirement for Incoming and Outgoing transactions to have an Envelope.
With this, “Income” transactions that make money available for budgeting are possible.
At the same time, if a tracking error occurs, reconciling transactions are now possible.
Those either remove money from the budget that does not exist or add money that was not
tracked before (same as an income transaction).
Neither of those two types logically requires an Envelope.
=> feat: allow transactions to be created without an Envelope

api/docs.go, api/swagger.json, api/swagger.yaml, main.go, pkg/controllers/allocation.go, pkg/controllers/allocation_test.go, pkg/controllers/budget_test.go, pkg/controllers/envelope_test.go, pkg/httputil/error.go, pkg/models/allocation.go, pkg/models/envelope.go
BREAKING CHANGE: With this, allocations use RFC3339 timestamps like all other
resources in the Envelope Zero backend already do.
Resolves #85.
=> feat!: allocations now use RFC3339 timestamps instead of a Month and a Year (u)int

pkg/controllers/allocation_test.go, pkg/models/allocation.go
This fixes a bug where you could not create an allocation for the same month, even when they referenced different Envelopes.
=> fix: allocations need to be uniqe for (month, envelope), not only the month

pkg/controllers/budget.go, pkg/controllers/budget_test.go
With this, budgets can be filtered for empty values, e.g. all budgets
without a currency.
Part of #247.
=> fix: enable zero value filtering for budgets

internal/router/router.go, main.go
With this commit, the backend will stop accepting new connections on SIGINT or SIGTERM,
but allow existing requests to finish. This graceful shutdown has a timeout of
25 seconds.
Additionally, this removes the double timestamp from the production log format.
Resolves #69.
=> feat: add graceful shutdown

pkg/controllers/transaction.go, pkg/controllers/transaction_test.go
This adds the changes made to transaction creation in #273 to
the logic for transaction updates, too.
=> fix: allow transactions to be updated without an Envelope

pkg/httputil/query.go
ioutil is deprecated since 1.16, migrating away from it.
=> chore(deprecations): migrate from ioutil to io

api/docs.go, api/swagger.json, api/swagger.yaml, internal/router/router.go, internal/router/router_test.go, pkg/controllers/cleanup.go, pkg/controllers/cleanup_test.go, pkg/controllers/main_list_test.go, pkg/controllers/main_options_test.go, pkg/httputil/options.go, pkg/httputil/options_test.go
This endpoint allows you to delete all resources permanently.
It can be used to reset an instance to “factory defaults“
=> feat: add cleanup for all resources

pkg/models/budget.go, pkg/models/budget_test.go
When calculating sums over transactions for a budget, the query
should filter transactions by the budget.
=> fix: only calculate with transactions for the budget

pkg/models/budget.go, pkg/models/budget_test.go
Enables calculation of total overspend for a month. Needed to calculate the sum available to budget in the next month.
Required for #41.
=> feat: add overspent for month calculation

pkg/models/budget.go, pkg/models/budget_test.go
The total budgeted amount is used for the calculation of the sum
available to budget. Therefore, only transactions before the month
in question may be added to the calculation.
=> fix: total budgeted before month

pkg/models/budget.go, pkg/models/budget_test.go
This adds transactions without an envelope to the overspent sum.
=> fix: overspent now adds transactions without envelope

pkg/controllers/budget.go, pkg/controllers/budget_test.go, pkg/models/budget.go
Fixes a bug where the Balance of a budget was summed up twice and added.
=> fix: budget balance not double the actual balance anymore

.github/.codecov.yml
With this, the checks will always succeed, even if the coverage is
outside of thresholds.
=> test: make codecov status informational

.golangci.yml, main.go
This reduces the cyclomatic complexity of the main function and makes golang-ci lint fail when it goes above 15.
=> refactor: move database init to function, reduce gocyclo limit

docs/upgrading.md, main.go
Cleans up migration code that is not needed after v1.0.0
=> refactor: remove old code

.github/workflows/pre-commit.yml, .github/workflows/test-and-release.yml, renovate.json
Updates the renovate config to automate more upgrades.
Also updates the hint for how to test go upgrades against swagger.
=> chore(renovate): update config for golangci-lint lang-version and upgarde hints

renovate.json
Uses docker versioning for golangci-lint go version as we need only major.minor
=> chore(renovate): fix versioning for golangci-lint language version

CONTRIBUTING.md
Clarifies versioning and dependency only release version bumps.
=> docs: document version increase when only dependencies are updated

main.go, pkg/router/router.go, pkg/router/router_test.go, test/helpers.go
This breaks up the router configuration in multiple functions, allowing for better reusability.
=> refactor: break up router setup into multiple functions

main.go
This fixes a regression in 9c9e365c6ada93d94e90eae85704f14b8afaa4c9 that led to the backend not starting.
=> fix: explicitly initialize database in main.go

.github/actions/go-test/action.yml
This prevents regressions like in 9c9e365c6ada93d94e90eae85704f14b8afaa4c9.
It builds the binary and starts it. If it does not exit within 3 seconds, it is killed, but the status reported as successful.
=> test: add test with timeout

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/budget.go, pkg/controllers/envelope.go, pkg/controllers/month.go, pkg/controllers/month_test.go, pkg/models/budget.go, pkg/models/budget_test.go, pkg/models/database_test.go, pkg/models/envelope.go, pkg/models/month.go, pkg/models/test_suite_test.go, pkg/router/router.go
This is part of #358. 
It adds a new `/v1/months?budget={budgetId}&month={month}` endpoint that replaces the existing `/v1/budgets/{budgetId}/{month}`, which is deprecated with this PR.
=> feat: add grouped month endpoint

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/router/router.go, pkg/router/router_test.go
Adds the missing link to the `months` endpoint.
=> fix: missing links to months endpoint

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/month.go, pkg/controllers/month_test.go, pkg/models/month.go
Adds a `balance` field with the sum of all envelopes.
=> feat: add envelope balance sum to month response

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/budget.go, pkg/controllers/envelope.go, pkg/controllers/month.go, pkg/controllers/month_test.go, pkg/models/envelope.go, pkg/models/envelope_test.go
This allows clients to easily modify the existing allocation if one exists or determine that they need to create a new one.
=> feat: add allocation link to month responses

pkg/controllers/month.go, pkg/controllers/month_test.go
With this commit, the allocation link for a month without an allocation
points to the collection endpoint. This enables clients to send a POST
request to that endpoint, creating a new allocation, whenever the
budgeted amount for that month is 0.
Before, clients needed to have the URL hardcoded or request it from
the API root, which is not good API design.
=> fix: allocation link for envelope month calculation

renovate.json
With this PR, minor updates for regex manager-managed dependencies are automerged, too.
=> chore(renovate): automerge regex manager updates, too

.gitignore, .golangci.yml, api/docs.go, api/swagger.json, api/swagger.yaml, docs/import.md, go.mod, go.sum, pkg/controllers/budget_test.go, pkg/controllers/import.go, pkg/controllers/import_test.go, pkg/controllers/month_test.go, pkg/controllers/test_options_test.go, pkg/httputil/options.go, pkg/httputil/options_test.go, pkg/importer/creator.go, pkg/importer/parser/ynab4/parse.go, pkg/importer/parser/ynab4/parse_test.go, pkg/importer/parser/ynab4/types.go, pkg/importer/types/types.go, pkg/router/router.go, pkg/router/router_test.go, test/helpers.go, testdata/Budget.yfull, testdata/wrong-name.json
This adds the `/v1/import` endpoint which enables the importing of YNAB 4 budgets. Please read through [the import documentation](https://github.com/envelope-zero/backend/blob/275b5a3032d142b0b97a266ce2750863078a07a0/docs/import.md) to understand the current state of importing and supported features.
Resolves #369.
=> feat: add import for YNAB 4 budgets

renovate.json
The x/exp modules used get digest updates. Those should be automerged, too.
=> chore(renovate): automerge digest updates, too

pkg/router/router.go
=> fix: return JSON error object instead of plain string for HTTP 405 responses

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/budget.go, pkg/controllers/budget_test.go, pkg/controllers/month.go, pkg/controllers/month_test.go, pkg/httputil/options.go, pkg/httputil/options_test.go
This adds new endpoints that fit better into the overall structure of the API.
Deprecates the existing endpoints.
Resolves #358.
=> feat: add new endpoints for allocation setting/deleting of a whole month

pkg/controllers/account_test.go, pkg/controllers/allocation_test.go, pkg/controllers/budget_test.go, pkg/controllers/category_test.go, pkg/controllers/cleanup_test.go, pkg/controllers/envelope_test.go, pkg/controllers/import_test.go, pkg/controllers/month_test.go, pkg/controllers/test_helpers_test.go, pkg/controllers/test_list_test.go, pkg/controllers/transaction_test.go, pkg/router/router_test.go, test/helpers.go
Cleans up unnecessary complication in testing helpers.
Resolves #360.
=> refactor: remove unnecessary parameters from test helpers

main.go, pkg/router/router.go
With this, the version of the backend is printed in INFO severity when starting up.
Resolves #364.
=> feat: print version when starting

README.md
Documents the current public API so that other developers can rely on our version numbering.
=> docs: start public API documentation

pkg/controllers/database.go
This fixes a bug where the log would prompt for a backend restart on any
unknown database error. This does not make sense as e.g. unique constraint
errors are not connection errors, but data errors that need to be fixed
by the user or client.
This also turns off logging for "not found" errors where no record exists that
matches the query as this could be confusing when analyzing the log - a record
not existing is not an error in the sense of our functionality here.
=> fix: do not prompt for restart on any db error, do not log not found errors

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/account.go, pkg/controllers/allocation.go, pkg/controllers/budget.go, pkg/controllers/category.go, pkg/controllers/envelope.go, pkg/controllers/month.go, pkg/controllers/month_config.go, pkg/controllers/month_config_test.go, pkg/controllers/test_options_test.go, pkg/controllers/transaction.go, pkg/controllers/types.go, pkg/models/account.go, pkg/models/allocation.go, pkg/models/budget.go, pkg/models/category.go, pkg/models/database.go, pkg/models/envelope.go, pkg/models/model.go, pkg/models/model_test.go, pkg/models/month_config.go, pkg/models/transaction.go, pkg/router/router.go
This PR adds the **MonthConfigs** resource. With that resource, configurations for a month can be stored.
Allocations will be migrated to this resource later, see #440.
Commits:
- chore: split model into ID and Timestamps
- feat: add month-config resource and API endpoints
- docs: remove double declaration of route config
=> feat: MonthConfigs

pkg/controllers/cleanup.go, pkg/controllers/cleanup_test.go
This adds MonthConfigs to the DELETE /v1 cleanup endpoint.
=> fix: clean up MonthConfigs with DELETE /v1

.goreleaser.yaml
With this change, all commits are included in the changelog. This makes 
the changelog less confusing when cross-referencing commits to the changelog.
=> ci: do not exclude any commits from the changelog

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/month_config.go
Fixes a copy-paste error for the API documentation.
=> docs: fix wrong description of MonthConfigs PATCH API endpoint

.golangci.yml, pkg/importer/creator.go, pkg/importer/parser/ynab4/parse.go, testdata/Budget.yfull
This fixes a bug where the amounts for transactions were not set correctly when importing split transactions from YNAB 4.
=> fix(import): negative amounts for YNAB4 import when importing split transactions

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/import.go
Fixes API documentation that contained information about planned features.
As those are not implemented yet, they should not be documented like they were.
=> docs: correct API documentation for import endpoint

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/import.go, pkg/controllers/import_test.go
This makes the YNAB 4 import available at `/v1/import/ynab4` as preparation for #465.
=> feat: make ynab4 import available at /v1/import/ynab4

pkg/importer/parser/ynab4/parse.go
Fixes an error with YNAB 4 imports that incorrectly imported split transactions when the split does not have a Category or is an Income transaction.
=> fix: unset envelope for subtransaction in YNAB 4 import if not defined

pkg/importer/parser/ynab4/parse.go
When importing from YNAB 4, we account for the different mode handling
of the overspend mode by setting the overspend mode to `AFFECT_ENVELOPE`
for all months up to and including the month when the import happens.
This PR fixes the handling so that it actually includes the `AFFECT_ENVELOPE` setting.
=> fix: add missing overspend mode when importing from YNAB4

.golangci.yml, pkg/models/budget_test.go, pkg/models/envelope.go, pkg/models/month_config.go
This fixes various bugs in the calculation of envelope balances.
Envelope balances now also take overspend handling into account.
Resolves #327.
=> fix: wrong calculation of envelope balance

docs/import.md
Updates the API endpoint for YNAB 4 imports to the one introduced in #467.
=> docs: update import link

.golangci.yml, renovate.json
By default, gofumpt uses the language version from go.mod,
which reduces the need for maintenance here.
=> test(golangci-lint): remove explicit version for gofumpt

.golangci.yml, pkg/controllers/account.go, pkg/controllers/allocation.go, pkg/controllers/budget.go, pkg/controllers/category.go, pkg/controllers/cleanup.go, pkg/controllers/envelope.go, pkg/controllers/import.go, pkg/controllers/month.go, pkg/controllers/month_config.go, pkg/controllers/transaction.go, pkg/router/router.go
go 1.19 introduced more features for documentation comments.
swagger switching to use tabs to indent (https://github.com/swaggo/swag/pull/1386) broke the formatting for the backend since it did not have any actual go docs beyond the swagger comments yet.
With this PR, go docs are added, resolving this issue.
=> docs: update funcs documentation with go 1.19 doc standards

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/month.go, pkg/controllers/month_test.go, pkg/models/month.go
This adds more fields to the /v1/month endpoint:
* `data` now has an additional `allocations` field that contains the
sum of all allocations for the month
* All categories (in `data.categories`) now have the following
additional fields:
* `balance`: Sum of all allocations for envelopes in that category
* `allocation`: Sum of all allocations for that category
* `spent`: Sum of spend for all envelopes
Resolves #485.
=> feat: add more fields to month endpoint

.golangci.yml, pkg/controllers/transaction.go, pkg/controllers/transaction_test.go
Transfers between two on-budget accounts must not have an envelope set.
Such a transaction would be incoming and outgoing for the envelope at
the same time, which is not possible.
Resolves #472.
=> fix: disallow transfers between two on-budget accounts with an envelope set

pkg/controllers/account.go, pkg/controllers/account_test.go, pkg/controllers/allocation.go, pkg/controllers/budget.go, pkg/controllers/budget_test.go, pkg/controllers/category.go, pkg/controllers/category_test.go, pkg/controllers/envelope.go, pkg/controllers/envelope_test.go, pkg/controllers/month_config.go, pkg/controllers/transaction.go, pkg/controllers/transaction_test.go, pkg/httputil/query.go, pkg/httputil/query_test.go
This PR updates the filtering logic to treat all string field filter (name & note)
as a “contains“ filter. 
For example, a note filter on “Hello”, will match all notes that contain the word
“Hello“ anywhere in the text.
- refactor: rename createField to filterField and improve documentation
- refactor: add setField return for GetURLFields
- feat: treat account name and note filter parameters like "contains"
- feat: treat budget name and note filter parameters like "contains"
- feat: treat category name and note filter parameters like "contains"
- feat: treat envelope name and note filter parameters like "contains"
- feat: treat transaction note filter parameters like "contains"
Resolves #459.
=> feat: wider matching

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/account.go, pkg/models/account.go, pkg/models/account_test.go
An account object now always includes a `recentEnvelopes` field.
This field contains the envelopes of transactions for which the account was the destination account.
For this field, only the last 10 transactions where the account was the destination account are checked.
The envelopes are sorted by frequency of use, most used envelope first.
Resolves #460.
=> feat: add commonly used envelopes for destination accounts to account object

pkg/controllers/transaction.go, pkg/controllers/transaction_test.go
- refactor: check transactions update & create in an extra function
- fix: transactions between two accounts are not possible
Resolves #366.
=> fix: transactions between external accounts

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/importer/parser/ynab4/parse.go, pkg/models/account.go
With this, the initial balance of an account can be set to a specific date so that
calculations prior to creation of the account can be correct, e.g. the sum available
to budget.
The YNAB 4 importer sets the initial balance date automatically from the YNAB 4
starting balance transactions.
=> feat: add date for initial balance

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/import.go, pkg/controllers/import_test.go, pkg/importer/creator.go
This fixes the HTTP response for the budget import which was erroneously set to return a HTTP status of 204.
It now returns HTTP 201 Created and the budget data.
=> fix: return HTTP 201 with budget object instead of 204 on import

pkg/controllers/account.go, pkg/controllers/account_test.go, pkg/controllers/category.go, pkg/controllers/category_test.go, pkg/controllers/envelope.go, pkg/controllers/envelope_test.go
Adds hidden query filters for all resources that have a `hidden` attribute.
- feat: add filtering for hidden accounts
- feat: add filtering for hidden categories
- feat: add filtering for hidden envelopes
Resolves #532.
=> feat: hidden query filters

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/account.go, pkg/controllers/category.go, pkg/controllers/envelope.go
This adds the missing `hidden` query parameters to the API documentation.
=> fix: add hidden query parameter to swagger

pkg/models/database.go
This fixes a bug where boolean fields are NULL for columns that are
created when rows already exist. For these rows, the column is NULL,
which gorm doesn't handle well since we can only query for true of false.
This commit introduces a migration that updates those fields to the default
value, which is always false for booleans.
It's unclear if this is intended or an upstream bug in gorm, therefore I filed
https://github.com/go-gorm/gorm/issues/5968.
=> fix: some boolean fields are NULL

.goreleaser.yaml, Dockerfile
With this, we're being good OCI citizens (or something like that)
by telling people where to find the source for the image.
Plus, renovate uses the org.opencontainers.image.source label to
find the source for changelogs, so it will now also show changelogs.
=> fix: add labels to OCI image

.goreleaser.yaml
This removes an unneeded and deprecated parameter.
=> chore: remove deprecated goreleaser config

.github/workflows/test-and-tag.yml
Updates the semver version comment to the exact version to have easier references in future updates.
=> chore(deps): pin codecov-action to 3.1.1

pkg/controllers/transaction.go, pkg/controllers/transaction_test.go
The OR must be applied only to the source and destination account ID,
not to the whole query.
Resolves #556.
=> fix: transaction filter for 'account' now correctly ORed in query

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/budget_test.go, pkg/controllers/envelope_test.go, pkg/models/budget.go, pkg/models/budget_test.go, pkg/models/category.go, pkg/models/envelope.go, pkg/models/model.go
With this change, all fields for categories and envelopes are
always included in queries to the month endpoint.
Resolves #552.
=> feat: always include all resource fields in month response

README.md
The backend is built with the goal of providing an HTTP API. This means that
the go module itself does not need to be part of the public API to guarantee
stable versioning for users.
If other projects do start relying on it as a go module and deem a more stable
approach necessary, their maintainers are welcome to open an issue to discuss
adding the exported functions and methods to the public API definition for this.
For now however, it will not be part of the public API.
Resolves #423.
=> docs: finish public API definition

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/account.go, pkg/controllers/account_test.go, pkg/controllers/budget.go, pkg/controllers/budget_test.go, pkg/controllers/category.go, pkg/controllers/category_test.go, pkg/controllers/envelope.go, pkg/controllers/envelope_test.go, pkg/controllers/filters.go
With the new 'search' query parameter for the list endpoints, all
string fields of a resource can be searched at the same time.
Resolves #554.
=> feat: add search parameter for all resources with name and note

pkg/importer/parser/ynab4/parse.go, pkg/importer/parser/ynab4/types.go, testdata/importer/Budget.yfull
This fixes a bug where the importer did not ignore budgeted (= allocated) amounts for deleted categories (= envelopes).
=> fix(import/ynab4): do not import budgeted amounts for deleted categories

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/month_config_test.go, pkg/models/month_config.go
This adds a note field for the MonthConfig model.
Resolves #630.
=> feat: add note field for MonthConfig

renovate.json
This will lead to #634 being automatically closed.
Follow https://github.com/swaggo/gin-swagger/issues/264 for updates.
=> chore(deps): pin swaggo/files to 1.0.1 since gin-swagger 1.x is not compatible with swaggo/files 2.x

pkg/importer/helpers/sha256.go, pkg/importer/helpers/sha256_test.go, pkg/importer/parser/ynab4/parse.go, pkg/models/database.go
This fixes a bug where the import hash was the string representation
of a slice containing the bytes for the SHA256 hash.
Import hashes are now always the hexadecimal string representation
of the SHA256 hash.
Resolves #628.
=> fix: import hashes should be a hex string of the bytes

pkg/models/envelope.go, pkg/models/envelope_test.go
This fixes a bug where deleted resources were included in the balance
calculation for an envelope, yielding wrong results.
=> fix: ignore deleted resources in calculation of balance for envelope

pkg/controllers/allocation_test.go, pkg/controllers/month.go, pkg/httperrors/errors.go, pkg/models/allocation.go, pkg/models/database.go
Allocations with an amount of 0 are useless and we don't need them.
Therefore, we disallow them.
Existing ones are deleted in a migration, too.
=> fix: do not allow allocations with amount 0

pkg/controllers/account_test.go, pkg/controllers/allocation_test.go, pkg/controllers/budget_test.go, pkg/controllers/category_test.go, pkg/controllers/cleanup_test.go, pkg/controllers/envelope_test.go, pkg/controllers/month_config_test.go, pkg/controllers/month_test.go, pkg/controllers/test_helpers_test.go, pkg/controllers/test_list_test.go, pkg/controllers/transaction_test.go
Move `assertHTTPStatus` to a function so that it does not require the suite.
This is needed for table tests to use the correct `*testing.T` when they are
reporting errors.
=> test: move assertHTTPStatus to a function

pkg/controllers/account_test.go, pkg/controllers/budget.go, pkg/controllers/budget_test.go, pkg/controllers/transaction_test.go, pkg/models/account.go, pkg/models/budget.go, pkg/models/budget_test.go
This reduces the length of the method chain that we are calling.
It should not impact performance.
=> refactor: move calculations to gorm hook methods

pkg/controllers/account.go, pkg/controllers/allocation.go, pkg/controllers/budget.go, pkg/controllers/category.go, pkg/controllers/envelope.go, pkg/controllers/generics.go, pkg/controllers/month.go, pkg/controllers/month_config.go, pkg/controllers/month_test.go, pkg/controllers/transaction.go, pkg/models/account.go, pkg/models/allocation.go, pkg/models/budget.go, pkg/models/category.go, pkg/models/envelope.go, pkg/models/model.go, pkg/models/transaction.go
This reduces redundant code.
Part of #618.
=> refactor: move getXObject into a generic function

pkg/controllers/month.go, pkg/controllers/month_test.go
This fixes a bug where using the quick allocation feature with the amount allocated last month would also allocate for archived envelopes.
=> fix: do not quick allocate for archived envelopes

renovate.json
This updates the renovate config to make use of useful templates for package grouping and replacements.
=> chore(deps): make renovate use some presets for grouping and package replacement

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/import.go, pkg/controllers/import_test.go, pkg/importer/parser/ynab-import/parse.go, pkg/importer/parser/ynab-import/parse_test.go, pkg/importer/types.go
This fixes multiple bugs in the YNAB import preview endpoint and parsing.
- return a list of TransactionCreate resources, not Transaction resources
- name the TransactionCreate resource "transaction" in the list
- only use positive amounts
=> fix(importer/ynab-import): fix initial bugs

pkg/controllers/import.go, pkg/controllers/import_test.go, testdata/importer/ynab-import/account-find-test.csv
This automatically sets existing accounts when their names match and are unique. Therefore, transaction imports become easier.
=> feat(importer/ynab-import): automatically use existing accounts with matching names

pkg/controllers/import.go, pkg/controllers/import_test.go
This fixes a bug where duplicate detection would also detect a transaction from a different budget with the same import hash as duplicate.
=> fix: verify that duplicate detection is only performed for the same budget

.github/workflows/bump-patch.yml
This removes the `needs` that was erroneously copy-pasted.
=> ci: fix copy-paste "needs" error

README.md
- The [readme states](https://github.com/envelope-zero/backend/blob/1ecdf9059848322827eb72e6280087dc53520f5a/README.md#L53) `Only set this when you want to use sqlite as database backend.` which sounds like different database backends are possible.
- But the code looks like only sqlite is supported: https://github.com/envelope-zero/backend/blob/1ecdf9059848322827eb72e6280087dc53520f5a/pkg/database/database.go#L30
=> docs: remove comment indicating that other database backends are supported

README.md
Small documentation improvement.
=> docs: add hint that CORS setting is only needed for frontend development

.gitignore, pkg/models/envelope.go, pkg/models/envelope_test.go
This modified the code added with 00ff02f4087d0229bc5e9588bc6e201b7cbcba1f so that
it only runs when the `hidden` field changes to `false`.
This should improve performance for all operations where that is not the case.
=> refactor: only run update on parent category when archival state changes to unarchived

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/import.go, pkg/controllers/import_test.go, pkg/importer/types.go
This adds the ID of the rename rule that mapped a transaction
preview to an account to the transaction preview.
=> feat: add rename rule to transaction preview

.github/workflows/release.yml
This removes the deprecated and unneeded `--rm-dist` option.
=> ci: remove unneded and deprecated option

.github/workflows/semantic-pr-merge-group.yml, .github/workflows/semantic-pr.yml
We can't run semantic PR checks in the merge group since it's missing the
PR context.
This adds a fake check to fix that
=> ci: satisfy required semantic-pr check on merge group

pkg/models/category.go, pkg/models/category_test.go
With this change, envelopes are archived automatically if their parent
category is archived.
Resolves #547.
=> feat: automatically archive envelopes when category is archived

pkg/models/account_test.go, pkg/models/budget_test.go, pkg/models/envelope_test.go
This uses the createTestX methods of the suite for model tests to make
test code shorter and less redundant.
Resolves #512.
=> test: use createTestX methods of suite

pkg/controllers/import_test.go, pkg/importer/parser/ynab-import/parse.go, testdata/importer/ynab-import/available-from-test.csv, testdata/importer/ynab-import/rename-rule-test.csv
=> fix: availableFrom now set to correct month for Import Previews

pkg/models/account_test.go, pkg/models/transaction.go, pkg/models/transaction_test.go
=> fix: availability date is now enforced to not be earlier than the month of the transaction

pkg/controllers/import.go, pkg/models/account.go, pkg/models/account_test.go
The RecentEnvelopes field for Account resources and the proposed Envelope for
ImportPreviews now also consider income transactions.
Income is represented as the nil UUID in the Envelope ID, meaning that the
RecentEnvelopes field will contain an entry with all zero-values for Income.
This will be improved in API v2 to replace the ID for income with a `null` value.
Resolves #773.
=> fix: income now recognized in RecentEnvelopes and transaction import

pkg/models/account.go
The recentEnvelopes are now sorted by number of occurences, date of the transactions
and the creation time of the envelope to guarantee the order to be deterministic.
=> fix: order of recentEnvelopes is now deterministic

pkg/controllers/transaction.go, pkg/controllers/transaction_test.go, pkg/models/transaction.go, pkg/models/transaction_test.go
When a Transaction is saved with a zero UUID for the Envelope,
the backend now explicitly sets the Envelope ID to nil.
This prevents errors when used in combination with the Transaction Preview
since the Transaction Preview returns the zero UUID for income.
=> fix: set Transaction Envelope ID to nil if it is the zero UUID

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/healthz.go, pkg/controllers/healthz_test.go, pkg/controllers/test_options_test.go, pkg/router/router.go
This adds the `/healthz` endpoint, which checks the health of the application.
For now, this mainly verifies that the database can be accessed.
Use this endpoint to automatically restart the backend with e.g. a docker compose
health check or Kubernetes probes.
It returns HTTP 204 for success and HTTP 500 with an error message when there is an error.
=> feat: add healthz endpoint

api/docs.go, api/swagger.json, api/swagger.yaml, commitlint.config.js, pkg/controllers/responses.go, pkg/controllers/transaction_v1.go, pkg/controllers/transaction_v1_test.go, pkg/controllers/transaction_v2.go, pkg/controllers/transaction_v2_test.go, pkg/models/transaction.go
This fixes the API v2 Transaction links by performing the same refactor
that was already performed for the Accounts.
=> fix: API v2 Transaction links

.github/workflows/test-and-tag.yml
With this change, PRs in the repo use the `CODECOV_TOKEN` to upload
coverage to codecov, while PRs from forks will keep using the upload
via the public API, which is suffering from rate limiting issues.
We can't fix the rate limiting issues, but at least we can work around it
for PRs by maintainers for now.
=> test: work around codecov token rate limit

.github/workflows/test-and-tag.yml, .vscode/settings.json
Just use the codecov token since it seems to work even when empty.
=> ci: add codecov token

pkg/controllers/account_v1.go, pkg/controllers/account_v2.go, pkg/controllers/allocation.go, pkg/controllers/budget.go, pkg/controllers/category.go, pkg/controllers/database.go, pkg/controllers/envelope.go, pkg/controllers/generics.go, pkg/controllers/match_rule.go, pkg/controllers/month.go, pkg/controllers/month_config.go, pkg/controllers/rename_rule.go, pkg/controllers/transaction_v1.go
With this, retries for DB failures are removed. This implementation has
never been completed.
Instead, use the `/healthz` endpoint to detect an unhealthy backend and
restart it.
Resolves #707.
=> refactor: remove retries from code

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/category.go, pkg/controllers/envelope.go, pkg/controllers/match_rule.go, pkg/controllers/match_rule_test.go, pkg/controllers/rename_rule.go, pkg/controllers/responses.go, pkg/models/match_rule.go
This continues the cleanup refactor with the MatchRules
=> refactor: move REST attributes to controller

pkg/importer/parser/ynab-import/parse.go, pkg/importer/parser/ynab-import/parse_test.go, testdata/importer/ynab-import/bank2ynab-ynap.csv, testdata/importer/ynab-import/error-amount-zero.csv
This fixes a bug where imports failed on a transaction with an amount of 0.
Since the backend can silently ignore these transactions, this change introduces
that exact behaviour.
=> fix: ignore transactions with amount of 0 on import

pkg/importer/creator.go, pkg/importer/parser/ynab4/parse.go, pkg/importer/parser/ynab4/parse_test.go, pkg/importer/types.go
This adds the import of "rename conditions" from YNAB4 to Match Rules.
Resolves #373.
=> feat: add Match Rule import to YNAB4 importer

pkg/httperrors/errors.go, pkg/httperrors/errors_test.go
This fixes an issue where the error was not surfaced through the API, but
only available in the backend log.
=> fix: show transactions with envelopes error to user when updating account

pkg/controllers/transaction_v1.go, pkg/controllers/transaction_v1_test.go
Before this fix, transactions would be sorted correctly by date, but
transactions later in a day would be after transactions earlier in the day.
When transactions were added for the exact same time (typically when importing),
sorting was undefined. Sorting for transactions at the same time now is "newest first"
by creation time, putting transactions added later earlier in the list.
Since the sorting is "newest first", this was wrong.
Sorting takes place with second precision, meaning that any sub-second differences
are ignored in sorting. This is a limitation of the sqlite `datetime` function.
=> fix: transaction sorting now takes time of day and creation time into account

Makefile, api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/account.go, pkg/controllers/allocation.go, pkg/controllers/category.go, pkg/controllers/database.go, pkg/controllers/envelope.go, pkg/controllers/generics.go, pkg/controllers/import.go, pkg/controllers/import_test.go, pkg/controllers/match_rule.go, pkg/controllers/month_config.go, pkg/controllers/rename_rule.go, pkg/controllers/responses.go, pkg/controllers/test_options_test.go, pkg/controllers/transaction.go, pkg/controllers/transaction_v1.go, pkg/controllers/transaction_v2.go, pkg/controllers/transaction_v3.go, pkg/controllers/transaction_v3_test.go, pkg/httperrors/errors.go, pkg/httperrors/errors_test.go, pkg/httperrors/types.go, pkg/httperrors/types_test.go, pkg/httputil/request.go, pkg/httputil/request_test.go, pkg/router/router.go, pkg/router/router_test.go
This adds the first endpoint for API v3: /v3/transactions.
It is the collection endpoint for Transactions, supporting pagination.
For transactions, the default `limit` is set to `50`.
=> feat: add /v3/transactions collection endpoint with GET support

README.md
This adds configuration documentation for the Kubernetes Liveness and Readiness Probes.
=> docs: add probe configuration

pkg/controllers/month_config_test.go, pkg/httperrors/errors.go, pkg/httperrors/errors_test.go
This defines the remaining errors in the httperrors package as exported variables.
=> refactor: define all errors as variables

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/transaction_v1.go, pkg/controllers/transaction_v2.go
This deprecates the endpoints that are already available in /v3.
=> chore: deprecate /v1/transactions and /v2/transactions endpoints

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/account_v1.go, pkg/controllers/allocation.go, pkg/controllers/budget.go, pkg/controllers/category.go, pkg/controllers/envelope.go, pkg/controllers/match_rule.go, pkg/controllers/month_config.go, pkg/controllers/rename_rule.go, pkg/controllers/transaction_v1.go, pkg/controllers/transaction_v3.go, pkg/controllers/transaction_v3_test.go, pkg/httperrors/errors.go, pkg/httperrors/errors_test.go, pkg/httputil/query.go, pkg/httputil/query_test.go
This adds the ability to PATCH and DELETE transaction resources.
=> feat: add PATCH and DELETE handling for /v3/transactions/{id}

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/responses.go, pkg/controllers/transaction_v3.go
This adds missing example error messages to the swagger API documentation.
=> docs: add examples for errors

pkg/models/category.go, pkg/models/category_test.go
=> fix: only archive envelopes in category when archiving a category

pkg/controllers/match_rule_v3.go, pkg/controllers/match_rule_v3_test.go
With this, Match Rules are sorted by priority first and the match second.
=> fix: sort Match Rules

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/transaction_v3.go
This removes the deprecated field from API v3 responses, where it should not have appeared in the first place.
It can still be used in requests, but will not have any effect since the field is ignored.
=> fix: remove reconciled field in API v3 responses

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/budget_v1.go
This adds the missing deprecation with the addition of /v3/budgets
=> chore: deprecate /v1/budgets endpoints

pkg/controllers/budget_v3.go
The default limit should be the same across all resources for consistency. This fixes the default limit for budgets.
=> fix: update default limit for budgets to 50

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/import_v3.go, pkg/controllers/import_v3_test.go, pkg/importer/parser/ynab-import/parse.go, pkg/importer/parser/ynab-import/parse_test.go, pkg/importer/types.go, testdata/importer/ynab-import/unparsed-file.csv
Resolves #865.
This also fixes a not yet discovered bug in the import preview parsing when unparseable CSV files were submitted.
=> fix: import error handling for broken CSV files, matchRuleId is null when there is no match

pkg/controllers/import_v3_test.go, pkg/controllers/transaction_v3_test.go
This will lead to better test failure messages and is already implemented
for all other v3 controller tests.
=> test: add *testing.T as first argument for createTestTransactionV3

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/allocation.go, pkg/controllers/month_config_v3.go, pkg/controllers/month_config_v3_test.go, pkg/models/month_config.go
Starting with this, allocations can be set directly on the MonthConfig with API v3 and do not need a separate application call.
Under the hood, API v3 still manages allocation resources to ensure that both API v1 and v3 function correctly.
=> feat: integrate allocations into MonthConfig in API v3

pkg/controllers/account_v3.go, pkg/controllers/account_v3_test.go, pkg/controllers/category_v3.go, pkg/controllers/category_v3_test.go, pkg/controllers/envelope_v3.go, pkg/controllers/envelope_v3_test.go, pkg/controllers/month_v3_test.go, pkg/httputil/request.go
This fixes a bug where the "archived" field was not updated when a PATCH request was sent.
=> fix: update archived field when PATCH request is sent

pkg/controllers/account_v3.go, pkg/controllers/account_v3_test.go, pkg/controllers/budget_v3.go, pkg/controllers/budget_v3_test.go, pkg/controllers/category_v3.go, pkg/controllers/category_v3_test.go, pkg/controllers/envelope_v3.go, pkg/controllers/envelope_v3_test.go, pkg/controllers/match_rule_v3.go, pkg/controllers/test_helpers_test.go, pkg/controllers/transaction_v3.go
This improves the handling of foreign key errors and not found messages in APIv3.
It also moves errors for resource creation to the specific resource, so that
a failure on creation of one resource does not affect all other resources.
With this, the status code for references to non-existing resources is also updated to
404 Not Found, instead of 400 Bad Request.
=> fix: improve foreign key and not found messages in API v3

pkg/models/account.go, pkg/models/account_test.go
This fixes an issue where income was not at the correct position in the
list of recommended envelopes as per the frequency it ocurrs with in the
recent transactions.
You will now see income being at the correct position in the recommended envelopes list.
=> fix: income at correct position in recommended envelopes

pkg/models/account.go, pkg/models/account_test.go, pkg/models/budget.go, pkg/models/budget_test.go, pkg/models/category.go, pkg/models/category_test.go, pkg/models/envelope.go, pkg/models/envelope_test.go, pkg/models/month_config.go, pkg/models/month_config_test.go, pkg/models/test_suite_test.go, pkg/models/transaction.go, pkg/models/transaction_test.go
With this change, all string fields will have whitespace trimmed from the start and end of the string.
This is especially useful when resource names must be unique as it is the case for categories, envelopes and accounts.
Resolves #887.
=> feat: trim whitespace from string fields

internal/types/month.go, internal/types/month_test.go
This fixes an issue where a variable of type types.Month could have
other parts than just year and month set, which was possible when
parsing it from user input.
This never surfaced since this has not been unmarshaled from user input yet
where the input could contain this.
However, this will be the case starting with goals.
Therefore, this bug is fixed now.
=> fix: Month JSON unmarshaling now enforcing year and month only

api/docs.go, api/swagger.json, api/swagger.yaml, internal/types/month.go, pkg/controllers/goals_v3.go, pkg/controllers/goals_v3_test.go, pkg/controllers/goals_v3_types.go, pkg/controllers/test_options_test.go, pkg/controllers/transaction_v3_test.go, pkg/httperrors/errors.go, pkg/httperrors/errors_test.go, pkg/importer/parser/ynab4/parse.go, pkg/models/database.go, pkg/models/errors.go, pkg/models/goal.go, pkg/models/goal_test.go, pkg/models/test_suite_test.go, pkg/router/router.go, pkg/router/router_test.go
This adds initial support goals, enabling users to create goals.
Note that there is no computation for these yet, so they're not
useful as of now.
Resolves #902.
=> feat: add goals

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/envelope_v3.go, pkg/controllers/month_v3.go, pkg/controllers/month_v3_test.go
This adds the envelope links to the month endpoint so that clients do not
need to compute their own URLs.
=> fix: add envelope links to month endpoint

.goreleaser.yaml
This fixes the use of labels to actually use labels.
=> fix: use labels for image correctly with goreleaser

.goreleaser.yaml
- Revert "fix: use labels for image correctly with goreleaser (#912)"
- Revert "feat: add linux/arm64 image (#911)"
=> fix: image build

pkg/controllers/month_v3.go, pkg/controllers/month_v3_test.go
This sorts the categories and envelopes alphabetically when calling the /v3/months endpoint.
=> feat: sorting of categories and envelopes for /v3/months

pkg/controllers/v4/transaction.go, pkg/controllers/v4/transaction_test.go
Filtering transactions by note was broken in API v4 before this
commit since the query did not specify the table name.
=> fix(v4): filtering transactions by note

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/v3/account.go, pkg/controllers/v3/budget.go, pkg/controllers/v3/category.go, pkg/controllers/v3/cleanup.go, pkg/controllers/v3/envelope.go, pkg/controllers/v3/goal.go, pkg/controllers/v3/import.go, pkg/controllers/v3/match_rule.go, pkg/controllers/v3/month.go, pkg/controllers/v3/month_config.go, pkg/controllers/v3/root.go, pkg/controllers/v3/transaction.go
chore: deprecate API v3
This deprecates API v3, since v4 is available now.
=> chore: deprecate API v3

SECURITY.md
Update contact email to the envelope-zero.org domain.
=> docs: update contact email address

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/v4/account.go, pkg/controllers/v4/account_test.go, pkg/controllers/v4/account_types.go
This marks archived envelopes as archived in the recent envelopes endpoint.
Resolves #973.
=> fix: mark archived envelopes as archived

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/v4/errors.go, pkg/controllers/v4/month.go, pkg/controllers/v4/transaction.go, pkg/controllers/v4/transaction_test.go, pkg/controllers/v4/transaction_types.go
This adds the ability to filter transactions by the transaction direction:
* Incoming: Funds moved from an off-budget to an on-budget account
* Outgoing: Funds moved from an on-budget to an off-budget account
* Transfer: Funds moved between internal accounts
Resolves #565
=> feat: implement transaction "direction" filter

.pre-commit-config.yaml, api/docs.go, api/swagger.json, api/swagger.yaml, go.mod, go.sum, pkg/controllers/v4/budget_types.go, pkg/controllers/v4/export.go, pkg/controllers/v4/export_test.go, pkg/controllers/v4/export_types.go, pkg/controllers/v4/test_options_test.go, pkg/models/account.go, pkg/models/account_test.go, pkg/models/budget.go, pkg/models/budget_test.go, pkg/models/category.go, pkg/models/category_test.go, pkg/models/envelope.go, pkg/models/envelope_test.go, pkg/models/goal.go, pkg/models/goal_test.go, pkg/models/interfaces.go, pkg/models/match_rule.go, pkg/models/match_rule_test.go, pkg/models/month_config.go, pkg/models/month_config_test.go, pkg/models/transaction.go, pkg/models/transaction_test.go, pkg/router/router.go, test/request.go
This adds functionality to export the whole state of the instance with an API call.
The API call to /v4/export returns a JSON object with some meta information:
* the version used to generate the export
* the creation time
With this change, go 1.22 is required since the tests now use range clauses over integers.
This commit also creates a registry for models so that we do not need to re-implement iteration over all models in the places we need it (database migrations, cleanup, …).
=> feat: add export

.golangci.yml, api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/v4/transaction.go, pkg/controllers/v4/transaction_test.go, pkg/controllers/v4/transaction_types.go
With this, transactions can be filtered by their "Available From" date.
Also disables gocyclo as linter since I've just been bumping the limit anyways.
Resolves #1004.
=> feat: add filtering of transactions by availability

pkg/controllers/v4/envelope.go, pkg/controllers/v4/envelope_test.go, pkg/controllers/v4/envelope_types.go, pkg/controllers/v4/goal.go, pkg/controllers/v4/goal_test.go, pkg/controllers/v4/goal_types.go, pkg/controllers/v4/match_rule.go, pkg/controllers/v4/match_rule_test.go, pkg/controllers/v4/match_rule_types.go
Envelopes, match rules and goals can now be filtered by all ancestors.
With this, clients can now request e.g. all envelopes for a budget instead of
requesting all categories and then having to loop over these, requesting all envelopes
for each category.
This partially implements #924, month configs still need to be added.
=> feat: filter by all ancestors

SECURITY.md
Better expectation management for vulnerabilities.
This adds more info about **who** maintains this and when to expect a reply.
=> docs: better expectation management for vulnerabilities

pkg/models/budget.go, pkg/models/budget_test.go
This fixes a bug in the budget income calculation, where transactions from internal off-budget
accounts were not counted towards income even when they are income.
Resolves #1007.
=> fix: budget income calculation

pkg/controllers/v4/transaction.go, pkg/controllers/v4/transaction_test.go, test/request.go
Requesting a transaction list with an invalid direction led to a response that was not valid JSON.
This was due to the Unmarshaling in tests not being done correctly.
This PR resolves the Unmarshal error and the broken response at the same time.
=> fix: response for wrong filter directions can now be unmarshaled

.pre-commit-config.yaml, api/docs.go, api/swagger.json, api/swagger.yaml, internal/uuid/uuid.go, internal/uuid/uuid_test.go, pkg/controllers/v4/account.go, pkg/controllers/v4/account_types.go, pkg/controllers/v4/budget.go, pkg/controllers/v4/category.go, pkg/controllers/v4/category_types.go, pkg/controllers/v4/envelope.go, pkg/controllers/v4/envelope_types.go, pkg/controllers/v4/goal.go, pkg/controllers/v4/goal_types.go, pkg/controllers/v4/import.go, pkg/controllers/v4/import_test.go, pkg/controllers/v4/match_rule.go, pkg/controllers/v4/match_rule_types.go, pkg/controllers/v4/month.go, pkg/controllers/v4/month_config.go, pkg/controllers/v4/month_config_test.go, pkg/controllers/v4/transaction.go, pkg/controllers/v4/transaction_types.go, pkg/controllers/v4/types.go, pkg/httputil/request.go, pkg/httputil/request_test.go
This removes the explicit UUID parsing in favor of an internal UUID implementation (wrapping google/uud) that 
includes the parsing methods for gin.
- **chore: remove UUID parsing**
- **chore: remove UUID parsing from account**
- **chore: remove UUID parsing from budget**
- **chore: remove UUID parsing from category**
- **chore: remove UUID parsing from envelope**
- **chore: remove UUID parsing from goal**
- **chore: remove UUID parsing from import**
- **chore: remove UUID parsing from match rule**
- **chore: remove UUID parsing from month config**
- **docs: improve documentation of /v4/months endpoint**
- **chore: remove UUID parsing from transaction**
- **chore: set format for URIID**
- **chore: only bind month URI once**
- **chore: move golangci-lint to the end to instantly reformat …
=> chore: remove UUID parsing

.github/workflows/test-and-tag.yml
Codecov now supports tokenless upload, so that's what we'll use from now on.
=> ci: do not set token anymore

pkg/controllers/v4/month_test.go, pkg/controllers/v4/transaction_test.go, pkg/models/budget_test.go, pkg/models/transaction.go
With this, the default AvailableFrom date is set to the first of the month following the transaction, not the month of the transaction.
This makes more sense logically since it enforces funds to only be allocated after they have been received by default.
The value can still be explicitly set if that is required.
=> feat!: set default available from to next month

api/docs.go, api/swagger.json, api/swagger.yaml, pkg/controllers/v4/errors.go, pkg/controllers/v4/transaction.go, pkg/controllers/v4/transaction_test.go, pkg/controllers/v4/transaction_types.go
Transaction filtering was incomplete and wrong so far, which is fixed with this change.
There are now two different filters, direction and type.
direction filters by the source/destination accounts being internal or external. It has the following values:
- IN: Transaction from an external to an internal account
- OUT: Transaction from an internal account to an external account
- INTERNAL: Transaction from an internal to an internal account (same as the old direction: TRANSFER)
type filters by the effect a transaction has on the budget. It has the following values
- INCOME: From an off-budget to an on-budget account (same as the old direction: INCOMING)
- SPEND: From an on-budget to an off-budget account (same as the old direction: OUTGOING)
- TRANSFER: From an on-budget to an on-budget …
=> fix: transaction filtering by direction and type

internal/controllers/v4/import_test.go, internal/importer/parser/ynab-import/parse.go
This PR sets the availableFrom month to the next month by default for imports.
I missed this in 51ba6793464e9ed029f6a6b6c796465648d0c881, so with this commit created transactions and imports behave the same again.
=> fix: set availableFrom to next month for imports

api/docs.go, api/swagger.json, api/swagger.yaml, internal/controllers/v4/budget_types.go, internal/controllers/v4/match_rule.go
This adds the match rules URL to the link list for a budget. Also adds the budget ID to the match rules GET endpoint documentation. The budget ID was already supported, but not documented yet.
=> fix: add URL for match rules to link list
