.github/semantic.yml
.github/workflows/pre-commit.yml
.pre-commit-config.yaml
CONTRIBUTING.md
go.mod
renovate.json

For more & better linting to prevent errors as early as possible.

test: add more linting configuration & documentation

---

internal/controllers/budget.go
internal/routing/routing.go

* Reorganizes code for the route registration
* Adds GET support to all endpoints
* Adds OPTIONS support to all endpoints

feat: support HTTP OPTIONS verb

---

.github/workflows/go-test.yml
go.mod
test/budget_test.go
test/helper.go
test/routing_test.go

This adds a few initial tests. There is a need for many more.

test: add initial testing

---

.github/workflows/pre-commit.yml
.golangci.yml
.pre-commit-config.yaml
.vscode/settings.json
CONTRIBUTING.md
internal/controllers/account.go
internal/controllers/budget.go
internal/controllers/category.go
internal/controllers/envelope.go
internal/controllers/transaction.go
internal/models/account.go
internal/models/database.go
internal/routing/routing.go
renovate.json

Simplifies the configuration and gives access to everything golangci-lint supports

test: move to golangci-lint

---

.github/workflows/go-test.yml

Corrects the name of the go test job

test: correct name for go test job

---

.github/workflows/go-test.yml

fix: missing data directory for tests

---

.github/workflows/build.yml
Dockerfile
go.mod

This adds a Dockerfile to build a runnable image.
It also adds a GitHub action workflow that builds the image and pushes it to the GitHub registry.

feat: add Dockerfile and build workflow

---

.github/workflows/build.yml

This change will build the image for tags, too.

fix: build image on tags, too

---

.gitignore
internal/models/database.go
main.go

When first checking out the repository there is no local folder called `data/` adding a `.gitkeep` into it changes that.

chore: create data directory with .gitkeep and other small things

---

Dockerfile

This disables CGO for the build as the final image is FROM scratch

fix: set CGO_ENABLED=0

---

.github/codecov.yml
.github/workflows/go-test.yml

Use codecov instead of self-written status output

test: add codecov

---

internal/models/account_test.go
internal/models/database_test.go
internal/models/main_test.go
internal/models/model_test.go
internal/models/transaction_test.go

This adds tests for all models that have methods

test: add tests for models

---

internal/controllers/account_test.go
internal/controllers/allocation_test.go
internal/controllers/budget_test.go
internal/controllers/category_test.go
internal/controllers/envelope_test.go
internal/controllers/transaction_test.go

test: use assort.Len

---

go.mod
go.sum
internal/controllers/account.go
internal/controllers/allocation.go
internal/controllers/budget.go
internal/controllers/category.go
internal/controllers/envelope.go
internal/controllers/helper.go
internal/controllers/main_error_handler_test.go
internal/controllers/routing.go
internal/controllers/transaction.go

Now with request IDs in both error messages and logs!

feat: add request IDs to error returns and logs

---

internal/controllers/account.go
internal/controllers/account_test.go
internal/models/account.go
internal/models/account_test.go

Accounts now also report the `reconciledBalance` which is the sum of all reconciled transactions.
Resolves #51.

feat: add sum of reconciled transactions

---

internal/models/database.go

gorm logger is now configured explicitly. With this, RecordNotFound errors won’t be logged anymore. 
See also #92 for remaining tasks.

feat: configure gorm logger

---

go.mod
go.sum
internal/models/database.go

With this, the gorm log format is the same as the others
Resolves #92.

feat: use gorm-zerolog

---

internal/models/database.go

5 times copy-pasting can save you 5 seconds of reading documentation.
`AutoMigrate` is a variadic function.

chore: boil down AutoMigrate calls to 1

---

internal/controllers/allocation_test.go
internal/controllers/envelope.go
internal/controllers/envelope_test.go

This adds the allocation amount to the month information endpoint

feat: add allocation to envelope month information

---

internal/controllers/budget.go
internal/controllers/budget_test.go
internal/controllers/envelope.go
internal/controllers/envelope_test.go
internal/controllers/helper.go
internal/models/budget.go
internal/models/envelope.go
internal/models/envelope_test.go

This resolves #43.
- chore: add envelope.Month method for monthly calculations
- feat: add Envelope ID, Envelope name and month to month calculation
- feat: add month endpoint for budgets

feat: envelope balances

---

.github/workflows/semantic-pr.yml

Adds semantic PR validation as an action

test: add semantic PR test as action

---

.github/workflows/semantic-pr.yml

The token needs to be explicitly specified

fix: add GITHUB_TOKEN to semantic PR check

---

docs/docs.go
docs/swagger.json
docs/swagger.yaml
internal/controllers/budget.go
internal/controllers/budget_test.go
internal/controllers/envelope.go
internal/controllers/envelope_test.go
internal/controllers/types.go

This splits the month endpoints into their own functions and updates the paths.

chore: split month endpoints

---

docs/api.md
internal/controllers/account.go
internal/controllers/account_test.go
internal/controllers/allocation_test.go
internal/controllers/budget.go
internal/controllers/budget_test.go
internal/controllers/category.go
internal/controllers/category_test.go
internal/controllers/envelope.go
internal/controllers/envelope_test.go
internal/controllers/main_test.go
internal/controllers/transaction.go
internal/controllers/transaction_test.go
internal/models/main_test.go
swag/docs.go
swag/swagger.json
swag/swagger.yaml

Budgets now use the new API layout from #125 and #136.

feat!: budgets with new API layout

---

internal/controllers/account.go
internal/controllers/budget.go
internal/controllers/main_list_test.go
internal/controllers/main_options_test.go
internal/controllers/routing.go
internal/controllers/transaction.go
internal/controllers/transaction_test.go
swag/docs.go
swag/swagger.json
swag/swagger.yaml

Transactions now also follow the new API scheme.

feat!: transactions now under API root and with links in data

---

.github/workflows/go-test-and-release.yml
.releaserc.yaml

Removes the steps pushing to main as this branch needs a PR.

chore: remove changelog generation

---

.goreleaser.yaml
Dockerfile.goreleaser

Create a goreleaser specific dockerfile to copy the binary to.

fix: goreleaser specific dockerfile

---

.github/workflows/go-test-and-release.yml

Should work according to
https://github.com/goreleaser/goreleaser-action/issues/261#issuecomment-1084828079

build: explicit login and GitHub token

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/account.go

Adds a link to the filtered transactions on accounts

feat: add transaction link to account

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/account.go
pkg/controllers/budget.go
pkg/controllers/budget_test.go
pkg/controllers/types.go

Enables filtering of budgets by name, note and currency.

feat: add filters for budget

---

docs/api.md

Update the API documentation and fix a typo

docs: update API documentation

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/models/account.go

This adds API examples for accounts.

feat: add swagger documentation for Account

---

pkg/controllers/main_test.go
pkg/models/account_test.go
pkg/models/all_test.go
pkg/models/envelope_test.go
pkg/models/main_test.go
pkg/models/model_test.go
pkg/models/transaction_test.go
pkg/test/helpers.go

Migrates the tests to use test suites, which are helpful to run a setup and tear down for every test.

test: migrate tests to use Suites

---

pkg/controllers/account_test.go
pkg/controllers/allocation_test.go
pkg/controllers/budget_test.go
pkg/controllers/category_test.go
pkg/controllers/envelope_test.go
pkg/controllers/main_test.go
pkg/controllers/transaction_test.go
pkg/test/helpers.go

This removes pre-created resources for tests to make it easier to write new tests.

test: remove pre-created resources for tests

---

.gitignore
Makefile

fix: version in API documentation

---

internal/router/router.go
main.go

fix: log level now initialized in main.go to prevent debug output on startup

---

.github/.codecov.yml
api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/category.go
pkg/controllers/category_test.go
pkg/controllers/envelope.go

feat: add envelope info to categories

---

pkg/models/account.go
pkg/models/allocation.go
pkg/models/budget.go
pkg/models/category.go
pkg/models/envelope.go
pkg/models/model.go
pkg/models/transaction.go

This makes interaction with the API easier since users can
rely on all fields being returned all the time, showing
all possible fields to set.

feat: always return all fields

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/account.go
pkg/controllers/allocation.go
pkg/controllers/budget.go
pkg/controllers/category.go
pkg/controllers/envelope.go
pkg/controllers/transaction.go

The API docs were outdated in some places, making them more complicated than needed.

fix: outdated API docs

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/envelope.go

This makes frontend coding much easier.

feat: add transactions link to envelope links

---

go.mod
pkg/controllers/account.go
pkg/controllers/account_test.go
pkg/controllers/allocation.go
pkg/controllers/allocation_test.go
pkg/controllers/budget.go
pkg/controllers/budget_test.go
pkg/controllers/category.go
pkg/controllers/category_test.go
pkg/controllers/envelope.go
pkg/controllers/envelope_test.go
pkg/controllers/transaction.go
pkg/controllers/transaction_test.go
pkg/httputil/error.go
pkg/httputil/error_test.go
pkg/httputil/query.go
pkg/httputil/query_test.go

fix: enable updating of zero values

---

pkg/controllers/allocation.go
pkg/controllers/transaction_test.go
pkg/httputil/error.go
pkg/models/transaction.go

fix: transactions need to have different source and destination accounts

---

internal/router/router_test.go
pkg/controllers/allocation_test.go
pkg/controllers/budget_test.go
pkg/controllers/category_test.go
pkg/controllers/envelope_test.go
pkg/controllers/main_list_test.go
pkg/controllers/main_options_test.go
pkg/controllers/transaction_test.go
pkg/httputil/options_test.go

test: use http.MethodX instead of plain string

---

README.md
docs/api.md
docs/upgrading.md

Update some documentation with upgrading instructions.

docs: documentation updates & upgrade steps

---

pkg/models/account.go
pkg/models/account_test.go
pkg/models/envelope_test.go

fix: do not add deleted transactions to account sum

---

pkg/controllers/budget_test.go
pkg/controllers/envelope_test.go
pkg/controllers/transaction.go
pkg/controllers/transaction_test.go
pkg/models/account_test.go
pkg/models/envelope_test.go
pkg/models/transaction.go

fix: allow transfers to not have an envelope

---

pkg/controllers/account.go
pkg/controllers/account_test.go
pkg/controllers/allocation.go
pkg/controllers/allocation_test.go
pkg/controllers/budget.go
pkg/controllers/budget_test.go
pkg/controllers/category.go
pkg/controllers/category_test.go
pkg/controllers/envelope.go
pkg/controllers/envelope_test.go
pkg/controllers/main_options_test.go
pkg/controllers/transaction.go
pkg/controllers/transaction_test.go

fix: requests with method OPTIONS now return 404 if the resource does not exist

---

renovate.json

chore: fix Makefile fileMatch

---

pkg/controllers/allocation.go
pkg/controllers/allocation_test.go

Adds query filtering for allocations. 
Part of #247.

feat: add query filters for allocations

---

pkg/controllers/allocation.go
pkg/controllers/allocation_test.go
pkg/controllers/category.go
pkg/controllers/category_test.go

Adds filtering for categories.
Part of #247.

feat: add query filters for categories

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/allocation.go
pkg/controllers/category.go
pkg/controllers/envelope.go
pkg/controllers/envelope_test.go
pkg/test/helpers.go

Adds query filtering for envelopes.
Part of #247.

feat: add query filters for envelopes

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/transaction.go
pkg/controllers/transaction_test.go
pkg/httputil/request.go

Now with query filtering for transactions.
Part of #247.

feat: add query filters for transactions

---

.golangci.yml
internal/router/middleware_test.go
pkg/controllers/category_test.go
pkg/controllers/envelope_test.go
pkg/httputil/error.go

Adds misspell and fixes current misspellings. 
Resolves #280.

test: add misspell

---

pkg/controllers/category.go
pkg/controllers/category_test.go
pkg/controllers/envelope.go
pkg/controllers/envelope_test.go
pkg/httputil/error.go
pkg/models/category.go
pkg/models/envelope.go

fix: make category and envelope names uniqe per budget/category

---

.vscode/launch.json
api/docs.go
api/swagger.json
api/swagger.yaml
go.mod
go.sum
pkg/controllers/transaction.go
pkg/controllers/transaction_test.go
pkg/httputil/query.go

Now with filtering for associated accounts regardless of them being source or destination.
Resolves #287.

feat: enable filtering of transactions by any account

---

pkg/controllers/account.go
pkg/controllers/allocation.go
pkg/controllers/budget.go
pkg/controllers/category.go
pkg/controllers/envelope.go
pkg/controllers/transaction.go

feat: improved error messages

---

pkg/controllers/budget.go
pkg/models/budget.go
pkg/models/budget_test.go

feat: add budget sum calculation

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/budget.go
pkg/controllers/budget_test.go
pkg/models/budget.go

feat: add budgeted sum for a month

---

api/docs.go
api/swagger.json
api/swagger.yaml
docs/usage.md
pkg/controllers/allocation.go
pkg/controllers/allocation_test.go
pkg/controllers/budget.go
pkg/controllers/budget_test.go
pkg/controllers/envelope.go
pkg/httperrors/errors.go
pkg/httperrors/errors_test.go
pkg/httputil/options.go
pkg/httputil/options_test.go

feat: add shortcut to delete all allocations for a month

---

main.go

Adds sub-second precision for log timestamps.

feat: increase timestamp precision in logs

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/budget.go

fix: add allocation month delete to Budgets group instead of new Budget group

---

.github/.codecov.yml
CONTRIBUTING.md

Updates documentation and CodeCov settings for current standards.

chore: relax test coverage threshold and update docs

---

.github/actions/go-test/action.yml
.github/workflows/pre-commit.yml
.github/workflows/test-and-release.yml
.github/workflows/test-and-tag.yml
.github/workflows/test.yml
.goreleaser.yaml
CONTRIBUTING.md
Makefile
README.md

This automates the releasing of new versions according to semantic commits and semantic versioning.

chore: update release flow to be fully automated

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/budget.go
pkg/controllers/budget_test.go
pkg/models/budget.go
pkg/models/budget_test.go

feat: add income to budget month calculations

---

docs/api.md
docs/database-schema.md
docs/usage.md

- docs: all HTTP 404 responses should contain an error message
- docs: add database schema document

docs: updates & database schema

---

Makefile

If you copy past, you got to do it right. I did not.

test: fix golangci-lint depName

---

pkg/models/budget.go
pkg/models/budget_test.go

Adds calculation for total income over all time, needed for #41.

feat: add total income calculation

---

pkg/models/budget.go
pkg/models/budget_test.go

feat: add total budgeted sum calculation

---

pkg/models/budget.go
pkg/models/budget_test.go

Total income is now calculated up to a certain month, so that the value is useful.

fix: total income calculated up to the specified month

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/budget.go
pkg/models/budget.go
pkg/models/budget_test.go

feat: sum available for budgeting

---

pkg/controllers/budget.go
pkg/controllers/budget_test.go
pkg/controllers/envelope_test.go
pkg/models/envelope.go
pkg/models/envelope_test.go

Fixes an issue where the sign of the `spend` sum was wrong.

fix: spend is positive when more was spent then taken in

---

renovate.json

This adds automerging for pre-commit and dockerfile dependencies.

chore: more automerging for renovate

---

main.go
pkg/controllers/account.go
pkg/controllers/account_test.go
pkg/controllers/allocation.go
pkg/controllers/allocation_test.go
pkg/controllers/budget.go
pkg/controllers/budget_test.go
pkg/controllers/category.go
pkg/controllers/category_test.go
pkg/controllers/cleanup_test.go
pkg/controllers/database.go
pkg/controllers/database_closed_test.go
pkg/controllers/envelope.go
pkg/controllers/envelope_test.go
pkg/controllers/main_list_test.go
pkg/controllers/main_options_test.go
pkg/controllers/main_test.go
pkg/controllers/transaction.go
pkg/controllers/transaction_test.go
pkg/httperrors/errors.go
pkg/httperrors/errors_test.go
pkg/models/account_test.go
pkg/models/budget_test.go
pkg/models/database_test.go
pkg/models/envelope_test.go
pkg/models/main_test.go
pkg/models/model_test.go
pkg/models/transaction_test.go

This PR introduces better error handling for database errors and makes preparations to allow for database connection retries.

fix: database error handling

---

pkg/controllers/account.go
pkg/controllers/allocation.go
pkg/controllers/budget.go
pkg/controllers/category.go
pkg/controllers/envelope.go
pkg/controllers/transaction.go

refactor: remove getXLinks functions

---

.gitignore
pkg/models/budget.go
pkg/models/budget_test.go
pkg/models/envelope.go
pkg/models/envelope_test.go

* Fixes the calculation of overspend.
* Fixes budget sum calculations at year end and start.

fix: budget calculations

---

api/docs.go
api/swagger.json
api/swagger.yaml
docs/usage.md
pkg/models/account.go
pkg/models/account_test.go

feat: add initial balance for accounts

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/models/account.go
pkg/models/category.go
pkg/models/envelope.go

feat: add hidden field for accounts, categories and envelopes

---

pkg/controllers/month_config.go
pkg/controllers/month_config_test.go

Fixes the broken links for MonthConfigs.

fix: add envelope link, fix zero padding for self link for MonthConfigs

---

pkg/importer/creator.go
pkg/importer/parser/ynab4/parse.go
pkg/importer/parser/ynab4/types.go
pkg/importer/types/types.go

Adds import of YNAB4 overspend handling to the /v1/import endpoint.

feat: import overspendingHandling config from YNAB4

---

.air.toml
.vscode/launch.json
README.md
go.mod
go.sum
pkg/router/router.go
pkg/router/router_test.go

This adds pprof endpoints. Enables better profiling of the application for development and debugging purposes.

feat: add pprof endpoints

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/month.go
pkg/controllers/month_test.go
pkg/models/month.go

Adds the spent sum for an entire month to the API.

feat: add month spent sum

---

.golangci.yml
api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/account.go
pkg/controllers/budget.go
pkg/importer/parser/ynab4/parse.go
pkg/importer/parser/ynab4/types.go
pkg/models/account.go
pkg/models/account_test.go
pkg/models/budget.go
pkg/models/budget_test.go
pkg/models/transaction.go

With this field, you can set for which month an income transaction
will be counted towards the available for budget sum.

feat: add AvailableFrom for income transactions

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/models/budget.go

chore: deprecate balance field

---

.github/workflows/test-and-tag.yml

this should fix the test & tag workflow not running on the main branch.

fix: add all branches to also run on main branch

---

.vscode/settings.json
api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/transaction.go
pkg/controllers/transaction_test.go

- feat: add ability to filter transactions by amount greater/smaller than a parameter
- style: formatting in VSCode
Resolves #557.

feat: filter transaction by amount

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/transaction.go
pkg/controllers/transaction_test.go

Fixes the misbehaving date filter for transactions and adds range filtering.

feat: date filters

---

.gitattributes

See the linguist documentation at https://github.com/github/linguist/blob/master/docs/overrides.md.

docs: add linguist overrides

---

.github/workflows/test-and-tag.yml

This pins the version of svu in use.

chore(deps): pin container version of svu

---

.github/workflows/test-and-tag.yml
renovate.json

This installs svu directly from the .tar.gz archive, which should 
bypass any errors that are related with the svu OCI image.

chore(deps): install svu from archive

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/models/transaction.go

Fixes an invalid example timestamp.

docs: fix an invalid RFC3339 timestamp

---

.github/workflows/test-and-tag.yml
renovate.json

This automates the udpate of svu.

chore(deps): add renovate comment to update svu

---

pkg/controllers/import.go
pkg/controllers/import_test.go

With this, the import preview endpoint pre-fills the envelope field with the most common recent envelope.

feat: pre-fill preview with most common recent envelope

---

.github/workflows/bump-patch.yml

This enables bumping the patch version manually.

ci: add manual patch version bumping

---

.github/workflows/pre-commit.yml
.github/workflows/test-and-tag.yml

This should fix checks not running correctly for PRs.

test: run tests on PRs and remove CODECOV_TOKEN

---

Makefile
api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/account.go
pkg/controllers/allocation.go
pkg/controllers/budget.go
pkg/controllers/category.go
pkg/controllers/envelope.go
pkg/controllers/generics.go
pkg/controllers/import.go
pkg/controllers/month.go
pkg/controllers/month_config.go
pkg/controllers/responses.go
pkg/controllers/test_options_test.go
pkg/controllers/transaction.go
pkg/controllers/transactionV1.go
pkg/controllers/transactionV2.go
pkg/controllers/transaction_test.go
pkg/httperrors/errors.go
pkg/httperrors/errors_test.go
pkg/httperrors/types.go
pkg/httperrors/types_test.go
pkg/models/allocation.go
pkg/models/errors.go
pkg/router/router.go
pkg/router/router_test.go
test/helpers.go

This introduces the first endpoint of API v2, transaction creation.
This endpoint allows bulk creation.

feat: add transaction create endpoint for v2

---

pkg/models/database.go
pkg/models/envelope.go
pkg/models/envelope_test.go

fix: unarchiving an envelope now also unarchives its parent category

---

pkg/controllers/import.go

This reduces the complexity and runtime of the transaction import transformations
by only looping over all of them once.

refactor: move loops out of functions, only loop over transactions for import once

---

pkg/controllers/import.go

I commented this during development and forgot to delete it.

chore: clean up commented code

---

pkg/controllers/import.go
pkg/controllers/import_test.go

This fixes the proposed envelope to work with rename rules.
Fixes #735.

fix: propose envelopes no matter how opposing account was found

---

pkg/controllers/transactionV1.go
pkg/controllers/transaction_test.go

fix: untilDate in transaction filter needs to be "before the next day"

---

pkg/controllers/transaction.go
pkg/models/account.go
pkg/models/account_test.go
pkg/models/database.go
pkg/models/database_test.go

fix: ensure that transfers do not have an envelope set

---

.github/workflows/pre-commit.yml
.github/workflows/renovate-config-validator.yml
.github/workflows/semantic-pr.yml
.github/workflows/test-and-tag.yml

This runs the required tests in the merge queue, allowing us to enable it

ci: enable merge queue

---

pkg/httperrors/errors.go
pkg/httperrors/errors_test.go
pkg/models/transaction.go

fix: error message for availability month is now passed to the user

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/allocation.go
pkg/controllers/envelope_test.go
pkg/controllers/month_config_test.go
pkg/controllers/month_test.go
pkg/controllers/test_suite_test.go
pkg/models/allocation.go
pkg/models/allocation_test.go

This continues the cleanup refactor with the Allocations.

refactor: move REST attributes to controller

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/test_create_test.go
pkg/controllers/transaction.go
pkg/controllers/transaction_v1_test.go
pkg/controllers/transaction_v3.go
pkg/controllers/transaction_v3_test.go
pkg/httputil/request.go

This adds the ability to get a single transaction to v3 of the API.

feat: add GET method for /v3/transactions/{id}

---

CONTRIBUTING.md

This details the config needed for air to work.

docs: add PATH hint

---

pkg/controllers/transaction_v3_test.go

Updates v3 tests to create transactions via the v3 API.

test: use v3 testing methods for v3 tests

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/cleanup_v3.go
pkg/controllers/cleanup_v3_test.go
pkg/httperrors/errors.go
pkg/router/router.go
pkg/router/router_test.go

For testing with v3. We might find a better solution for this in the future, though.

feat: add /v3 DELETE endpoint for cleanup

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/account_v1.go
pkg/controllers/account_v2.go
pkg/controllers/account_v3.go
pkg/controllers/account_v3_test.go
pkg/controllers/budget_v3_test.go
pkg/controllers/cleanup_v3_test.go
pkg/controllers/import_v3_test.go
pkg/controllers/match_rule_v3_test.go
pkg/controllers/test_options_test.go
pkg/controllers/transaction_v3.go
pkg/controllers/transaction_v3_test.go
pkg/router/router.go
pkg/router/router_test.go

This adds Accounts to the v3 API

feat: add /v3/accounts

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/cleanup.go
pkg/controllers/envelope_v3.go
pkg/controllers/month.go
pkg/controllers/month_config_v3.go
pkg/controllers/month_v1.go
pkg/controllers/month_v1_test.go
pkg/controllers/month_v3.go
pkg/controllers/month_v3_test.go
pkg/controllers/test_options_test.go
pkg/httperrors/errors.go
pkg/router/router.go
pkg/router/router_test.go

This adds the months endpoint to API v3. With this, API v3 is completed and all previous versions are deprecated.

feat: add months endpoints to API v3

---

.goreleaser.yaml

This adds the linux/arm64 architecture as a build target.

feat: add linux/arm64 image

---

docs/upgrading.md

fixes the headings in the upgrading notes.

docs: fix headings

---

pkg/controllers/v3/account_test.go
pkg/controllers/v3/budget_test.go
pkg/controllers/v3/category_test.go
pkg/controllers/v3/envelope_test.go
pkg/controllers/v3/month_test.go
pkg/controllers/v4/account_test.go
pkg/controllers/v4/budget_test.go
pkg/controllers/v4/category_test.go
pkg/controllers/v4/envelope_test.go
pkg/controllers/v4/month_test.go
pkg/importer/parser/ynab-import/parse_test.go
pkg/importer/parser/ynab4/parse_test.go
pkg/models/account_test.go

This makes tests easier to read and maintain.
Resolves #928.

test: replace "if !assert" with require

---

.pre-commit-config.yaml

chore(deps): move back to release version

---

pkg/controllers/v4/month.go
pkg/controllers/v4/month_test.go

This fixes a bug where the "quick allocation" feature at POST /v4/months
did not respect the selected budget and set allocations for all envelopes
in all budgets.
Resolves #972.

fix: quick allocation now respects the budget

---

Makefile

This implements the migration of the air repository.

chore: air has migrated repository, update Makefile

---

pkg/controllers/v4/account.go

Small documentation improvement.

docs: improve documentation of recent envelopes

---

api/docs.go
api/swagger.json
api/swagger.yaml
pkg/controllers/root/root.go
pkg/controllers/root/root_test.go

Fixes the links from root to v4.

docs: fix root links to v4

---

internal/controllers/v4/account.go
internal/controllers/v4/budget.go
internal/controllers/v4/category.go
internal/controllers/v4/envelope.go
internal/controllers/v4/generics.go
internal/controllers/v4/goal.go
internal/controllers/v4/match_rule.go
internal/controllers/v4/transaction.go

Refactors the controllers to use generics.

refactor: use generics for resource detail OPTIONS requests and DELETE requests

---

api/docs.go
api/swagger.json
api/swagger.yaml
internal/controllers/v4/goal.go
internal/controllers/v4/goal_test.go
internal/controllers/v4/goal_types.go
internal/models/goal.go

This adds recurrence for goals.
Resolves #904.

feat: add recurrence to goals
